# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tags',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='tags',
            new_name='category',
        ),
    ]
